TEMP_ARR = {
    'typ': -1,
    'cena': -1,
    'typ_transakcji': -1,
    'dostepny': -1,
    'powierzchnia': -1,
    'powierzchnia_dzialki': -1,
    'link': -1,
    'liczba_zdjec': -1,
    'zdjecia_linki': -1,
    'zdjecie_glowne': -1,
    'zdjecie_glowne_link': -1,
    'opis': -1,
    'rynek': -1,
    'liczba_pomieszczen': -1,
    'pietro': -1,
    'lokalizacja': -1,
    'cena_za_m2': -1,
    'typ_zabudowy': -1,
    'standard_wykonczenia': -1,
    'rok_budowy': -1,
    'balkon': -1,
    'miejsce_parkingowe': -1,
    'winda': -1,
    'stan_wykonczenia': -1,
    'piwnica': -1,
    'umeblowane': -1,
    'liczba_lazienek': -1,
    'numer_oferty': -1,
    'lokale_uzytkowe': -1,
    'oplaty': -1,
    'nr_oferty': -1,
    'budynek_pietra': -1,
    'kaucja': -1,
    'wystawa_okien': -1,
    'dojazd': -1,
    'stan_prawny_dzialki': -1,
    'telefon': -1,
    'email': -1,
    'nazwa_biura': -1,
    'data_dodania_oferty': -1,
    'data_skanowania': -1,
}

TEMPLATE = 'https://www.americanhome.pl/oferta/'

LINKS = [
    'https://www.americanhome.pl/oferty/mieszkania',
    'https://www.americanhome.pl/oferty/domy',
    'https://www.americanhome.pl/oferty/dzialki',
    'https://www.americanhome.pl/oferty/lokale']

FIELD_NAMES = {
    'typ': 'typ',
    'Cena': 'cena',
    'Typ transakcji': 'typ_transakcji',
    'dostepny': 'dostepny',
    'Powierzchnia': 'powierzchnia',
    'Powierzchnia działki': 'powierzchnia_dzialki',
    'link': 'link',
    'liczba_zdjec': 'liczba_zdjec',
    'zdjecia_linki': 'zdjecia_linki',
    'zdjecie_glowne': 'zdjecie_glowne',
    'zdjecie_glowne_link': 'zdjecie_glowne_link',
    'Rynek': 'rynek',
    'opis': 'opis',
    'Liczba pokoi': 'liczba_pomieszczen',
    'Piętro': 'pietro',
    'lokalizacja': 'lokalizacja',
    'Cena za m2': 'cena_za_m2',
    'Typ domu': 'typ_zabudowy',
    'Standard wykończenia': 'standard_wykonczenia',
    'Rok budowy': 'rok_budowy',
    'balkon': 'balkon',
    'Garaż/Miejsca parkingowe': 'miejsce_parkingowe',
    'winda': 'winda',
    'Stan nieruchomości': 'stan_wykonczenia',
    'piwnica': 'piwnica',
    'umeblowane': 'umeblowane',
    'liczba łazienek': 'liczba_lazienek',
    'Numer oferty': 'numer_oferty',
    'lokale użytkowe': 'lokale_uzytkowe',
    'Czynsz pln': 'oplaty',
    'Liczba pięter': 'budynek_pietra',
    'Kaucja': 'kaucja',
    'wystawa okien': 'wystawa_okien',
    'dojazd': 'dojazd',
    'stan prawny działki': 'stan_prawny_dzialki',
    'telefon': 'telefon',
    'email': 'email',
    'nazwa_biura': 'nazwa_biura',
    'data_dodania_oferty': 'data_dodania_oferty',
    'data_skanowania': 'data_skanowania',
}