TEMP_ARR = {
    'typ': -1,
    'cena': -1,
    'typ transakcji': -1,
    'dostepny': -1,
    'powierzchnia': -1,
    'powierzchnia działki': -1,
    'link': -1,
    'liczba_zdjec': -1,
    'zdjecia_linki': -1,
    'zdjecie_glowne': -1,
    'zdjecie_glowne_link': -1,
    'opis': -1,
    'rynek': -1,
    'liczba pomieszczeń': -1,
    'piętro': -1,
    'lokalizacja': -1,
    'cena za m2': -1,
    'typ zabudowy': -1,
    'standard_wykończenia': -1,
    'rok_budowy': -1,
    'balkon': -1,
    'miejsce_parkingowe': -1,
    'winda': -1,
    'stanwykonczenia': -1,
    'piwnica': -1,
    'umeblowane': -1,
    'liczba_łazienek': -1,
    'numer_oferty': -1,
    'lokale użytkowe': -1,
    'opłaty': -1,
    'nr_oferty': -1,
    'budynek_pietra': -1,
    'kaucja': -1,
    'wystawa okien': -1,
    'dojazd': -1,
    'stan prawny działki': -1,
    'telefon': -1,
    'email': -1,
    'nazwa_biura': -1,
    'data_dodania_oferty': -1,
    'data_skanowania': -1,
}

TEMPLATE = 'https://www.americanhome.pl/oferta/'

CSV_TYPES = [
    'typ',
    'cena',
    'typ transakcji',
    'dostepny',
    'powierzchnia',
    'powierzchnia działki',
    'link',
    'liczba_zdjec',
    'zdjecia_linki',
    'zdjecie_glowne',
    'zdjecie_glowne_link',
    'rynek',
    'opis',
    'liczba pomieszczeń',
    'piętro',
    'lokalizacja',
    'cena za m2',
    'typ zabudowy',
    'standard_wykończenia',
    'rok_budowy',
    'balkon',
    'miejsce_parkingowe',
    'winda',
    'stanwykonczenia',
    'piwnica',
    'umeblowane',
    'liczba_łazienek',
    'numer_oferty',
    'lokale użytkowe',
    'opłaty',
    'nr_oferty',
    'budynek_pietra',
    'kaucja',
    'wystawa okien',
    'dojazd',
    'stan prawny działki',
    'telefon',
    'email',
    'nazwa_biura',
    'data_dodania_oferty',
    'data_skanowania',
]

LINKS = [
    'https://www.americanhome.pl/oferty/mieszkania',
    'https://www.americanhome.pl/oferty/domy',
    'https://www.americanhome.pl/oferty/dzialki',
    'https://www.americanhome.pl/oferty/lokale']

FIELD_NAMES = {
    'typ': 'typ',
    'Cena': 'cena',
    'Typ transakcji': 'typ transakcji',
    'dostepny': 'dostepny',
    'Powierzchnia': 'powierzchnia',
    'Powierzchnia działki': 'powierzchnia działki',
    'link': 'link',
    'liczba_zdjec': 'liczba_zdjec',
    'zdjecia_linki': 'zdjecia_linki',
    'zdjecie_glowne': 'zdjecie_glowne',
    'zdjecie_glowne_link': 'zdjecie_glowne_link',
    'Rynek': 'rynek',
    'opis': 'opis',
    'Liczba pokoi': 'liczba pomieszczeń',
    'Piętro': 'piętro',
    'lokalizacja': 'lokalizacja',
    'Cena za m2': 'cena za m2',
    'Typ domu': 'typ zabudowy',
    'Standard wykończenia': 'standard_wykończenia',
    'Rok budowy': 'rok_budowy',
    'balkon': 'balkon',
    'Garaż/Miejsca parkingowe': 'miejsce_parkingowe',
    'winda': 'winda',
    'Stan nieruchomości': 'stanwykonczenia',
    'piwnica': 'piwnica',
    'umeblowane': 'umeblowane',
    'liczba łazienek': 'liczba_łazienek',
    'Numer oferty': 'numer_oferty',
    'lokale użytkowe': 'lokale użytkowe',
    'Czynsz pln': 'opłaty',
    'Liczba pięter': 'budynek_pietra',
    'Kaucja': 'kaucja',
    'wystawa okien': 'wystawa okien',
    'dojazd': 'dojazd',
    'stan prawny działki': 'stan prawny działki',
    'telefon': 'telefon',
    'email': 'email',
    'nazwa_biura': 'nazwa_biura',
    'data_dodania_oferty': 'data_dodania_oferty',
    'data_skanowania': 'data_skanowania',
}