import os

fieldNamesDict = {
    'typ': 'typ',
    'Cena': 'cena',
    'typ transakcji': 'typ transakcji',
    'dostepny': 'dostepny',
    'Powierzchnia': 'powierzchnia',
    'Powierzchnia działki': 'powierzchnia działki',
    'link': 'link',
    'liczba_zdjec': 'liczba_zdjec',
    'zdjecia_linki': 'zdjecia_linki',
    'zdjecie_glowne': 'zdjecie_glowne',
    'zdjecie_glowne_link': 'zdjecie_glowne_link',
    'Rynek': 'rynek',
    'opis': 'opis',
    'Liczba pokoi': 'liczba pomieszczeń',
    'Piętro': 'piętro',
    'lokalizacja': 'lokalizacja',
    'Cena za m2': 'cena za m2',
    'Typ domu': 'typ zabudowy',
    'standard_wykończenia': 'standard_wykończenia',
    'Rok budowy': 'rok_budowy',
    'balkon': 'balkon',
    'Garaż/Miejsca parkingowe': 'miejsce_parkingowe',
    'winda': 'winda',
    'Stan nieruchomości': 'stan_wykonczenia',
    'piwnica': 'piwnica',
    'umeblowane': 'umeblowane',
    'liczba_łazienek': 'liczba_łazienek',
    'numer_oferty': 'numer_oferty',
    'lokale użytkowe': 'lokale użytkowe',
    'Czynsz administracyjny': 'opłaty',
    'Numer oferty': 'nr_oferty',
    'Liczba pięter': 'budynek_pietra',
    'Kaucja': 'kaucja',
    'wystawa okien': 'wystawa okien',
    'dojazd': 'dojazd',
    'stan prawny działki': 'stan prawny działki',
    'telefon': 'telefon',
    'email': 'email',
    'nazwa_biura': 'nazwa_biura',
    'data_dodania_oferty': 'data_dodania_oferty',
    'data_skanowania': 'data_skanowania',
}
urlDomain = 'https://landowscy-nieruchomosci.pl'
urls = []
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
offerList = []
offset = 0
